### PR TITLE
Fix bug where mappers were run before batch was flushed

### LINKED ISSUE #25: Fix bug where mappers were run before batch was flushed

### PR DESCRIPTION
**Pull request by ganemone**
Fixes #25

### CODE REVIEW

File: src/server.js [hunk 1]
```diff
@@ -40,11 +40,10 @@ export default function() {
         }
       }
       emit(type, payload, ctx) {
-        payload = super.mapEvent(type, payload, this.ctx);
         if (!this.ctx) {
+          payload = super.mapEvent(type, payload, this.ctx);
```
Comment (KevinGrandon) [inline src/server.js]: Seems strange that we want to pass in a falsey ctx here?

**Comment by ganemone** [comment]
!merge
